version: "3.7"
services:
    php:
        build:
            args:
                USER: khuram
                uid: 1000
            context: ./docker-compose/php
            dockerfile: Dockerfile
        image: tdd-setup-php
        container_name: tdd-setup-php
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./:/var/www
        networks:
            - tdd_setup_php

    web:
        image: nginx:alpine
        container_name: tdd-setup-web
        restart: unless-stopped
        ports: 
            - 3070:80
        working_dir: /var/www
        # command: [nginx-debug, '-g', 'daemon off;']
        volumes:
            - ./:/var/www
            - ./docker-compose/nginx/conf.d:/etc/nginx/conf.d
            - ./docker-compose/nginx/nginx.conf:/etc/nginx/nginx.conf
        networks:
            - tdd_setup_php

volumes:
  _:

networks:
    tdd_setup_php:
        driver: bridge
